# Generated by Django 4.2.5 on 2023-09-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_char', models.CharField(max_length=255, unique=True)),
                ('test_int', models.IntegerField()),
                ('test_bool', models.BooleanField()),
            ],
            options={
                'db_table': 'test',
                'managed': True,
            },
        ),
    ]
