# Generated by Django 4.2.5 on 2023-09-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
