# Generated by Django 4.2.5 on 2023-09-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_delete_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='new_field',
        ),
    ]
